name: octonote
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.10.1

dependencies:
  auto_size_text: ^3.0.0
  fake_cloud_firestore: ^2.4.1
  bloc: ^8.0.2
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  easy_localization: ^3.0.0
  faker: ^2.0.0
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  formz: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  google_sign_in: ^5.3.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  shared_preferences: ^2.0.13
  sign_in_with_apple: ^3.3.0

  super_editor: ^0.2.6
  super_text_layout: ^0.1.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.0.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/svg/
