// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1aK-WlJJP8EuCgEbvUaLuHPrjbZHIeM',
    appId: '1:514353344314:web:0bab881de5883618b22a03',
    messagingSenderId: '514353344314',
    projectId: 'octonote',
    authDomain: 'octonote.firebaseapp.com',
    storageBucket: 'octonote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAis0TDY3rf14R3eJe3-OQzDtO1v-GmX28',
    appId: '1:514353344314:android:2bbba99cb95ab46ab22a03',
    messagingSenderId: '514353344314',
    projectId: 'octonote',
    storageBucket: 'octonote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzh0SM0lP9YlqYpJfCdk7IIXbCJl_WTDc',
    appId: '1:514353344314:ios:ea37b6ccce71f2c9b22a03',
    messagingSenderId: '514353344314',
    projectId: 'octonote',
    storageBucket: 'octonote.appspot.com',
    iosClientId: '514353344314-6livjfcuprr32mhfc3l1vcrrfvlmjd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.octonote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzh0SM0lP9YlqYpJfCdk7IIXbCJl_WTDc',
    appId: '1:514353344314:ios:ea37b6ccce71f2c9b22a03',
    messagingSenderId: '514353344314',
    projectId: 'octonote',
    storageBucket: 'octonote.appspot.com',
    iosClientId: '514353344314-6livjfcuprr32mhfc3l1vcrrfvlmjd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.octonote',
  );
}
