# This is the configuration file for your staging environment. The staging
# environment is meant to resemble the production environment as much as
# possible and may connect to production databases services and data. You use it
# for final testing before deploying the production server.
#
# To improve scalability and reliability it's possible to run Serverpod over a
# cluster of servers. The ids of the servers should be in a consecutive sequence
# from 0 to n-1 where n is the number of servers in your cluster.

# Defines public facing access to the server, in staging mode this will be
# the address of your staging load balancer or cloud front.
publicHost: api.staging.example.com
publicPort: 443
publicScheme: https

# Main port to run the server on.
port: 8080
# Service port, used for insights from the server while it's running.
servicePort: 8081

# This is the database setup for your servers. You will need to edit this to get
# the server up and running.
database:
  host: database.example.com
  port: 5432
  name: DATABASE_NAME
  user: DATABASE_USER

# This is the database setup for your servers. You will need to edit this to get
# the server up and running.
# This is the setup for Redis.
redis:
  host: redis.example.com
  port: 6379