name : CI
on:
  push:
     branches:
        - main
   pull_request:
     branches:
        - main
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
- uses: subosito/flutter-action@v2
  with:
    flutter-version: '2.10.2'
    channel: 'stable'
- run: flutter pub get
- run: flutter test
